### ISSUE TITLE
astro-critters v.2.0.0 has only empty package.json

### ISSUE THREAD

**Issue by zoxon** [PlayForm/Inline#136]
https://npmfs.com/package/astro-critters/2.0.0/
Previous versions does't work because `files-pipe` dependency was deleted from npm

**Comment by villanuevadani** [comment]
Having the issue with `files-pipe` as well

**Comment by GrantBirki** [comment]
related: https://github.com/astro-community/astro-critters/issues/137

**Comment by NikolaRHristov** [comment]
@zoxon, @villanuevadani, @GrantBirki - https://github.com/astro-community/astro-compress/issues/163#issuecomment-1668154678

**Comment by NikolaRHristov** [comment]
Fixed - https://github.com/astro-community/astro-critters/issues/137#issuecomment-1670887157
