### ISSUE TITLE
`files-pipe` dependency is not available anymore

### ISSUE THREAD

**Issue by villanuevadani** [PlayForm/Inline#137]
Looks like `files-pipe` dependency is not available anymore. I guess the lib should now rely on `files-pipeline`; could you please do the change?

<img width="987" alt="image" src="https://github.com/astro-community/astro-critters/assets/9211908/788c1373-48c2-42f1-ae11-9e9dc4eda198">

**Comment by GrantBirki** [comment]
I'm getting the exact same error as you and [all my ci jobs are failing](https://github.com/GrantBirki/astrowind/actions/runs/5783588888/job/15672666492#step:5:5)

**Comment by GrantBirki** [comment]
You can even still search for the `files-pipe` dependency on Google but the GitHub link immediately `404`s...

https://github.com/astro-community/astro-critters/assets/23362539/cffbba5a-563f-46fe-b7ff-f4c3e57cb5f0

**Comment by moritzlaube** [comment]
Same here. This is crashing Github Actions

**Comment by NikolaRHristov** [comment]
@villanuevadani, @GrantBirki, @moritzlaube - https://github.com/astro-community/astro-compress/issues/163#issuecomment-1668154678

**Comment by NikolaRHristov** [comment]
@villanuevadani, @GrantBirki, @moritzlaube `astro-critters` is up v2.0.2 with [Provenance](https://search.sigstore.dev/?logIndex=30616143)

This repository https://github.com/baxast/astro-critters will soon be synchronized with the official astro-community one https://github.com/astro-community/astro-critters. You can post issues in either.
