### ISSUE TITLE
Original critters options don't have any impact

### ISSUE THREAD

**Issue by drumsta** [PlayForm/Inline#67]
Hello,

I'm trying to fine tune critters process, but it seems [options ](https://github.com/GoogleChromeLabs/critters#critters-1) from original Critters don't have any impact at all.

The configuration file looks like below:
```
  integrations: [
    critters({
      minimumExternalSize: 1000000,
      keyframes: "all",
      pruneSource: true,
      noscriptFallback: false,
    }),
  ],
});
```

No one option listed above doesn't have any impact on the final build - builds look identically with or without these options.

Any ideas?

**Comment by NikolaRHristov** [comment]
`pruneSource` doesn't work at all. This has been referenced before (discussed offline) https://github.com/astro-community/astro-critters/issues/1 and there's a new issue about it - https://github.com/GoogleChromeLabs/critters/issues/111

I have created a new library (forked) that will fix this https://github.com/nikolaxhristov/critters

I don't know about the other options. You can try to manually invoke `critters` like in https://github.com/GoogleChromeLabs/critters/issues/111 to see if your changes have any effect at all.

**Comment by drumsta** [comment]
Thanks Nikola for your reply!

Are you going eventually to replace the dependency used in astro-critters to your new library mention in the answer above? Or will astro-critters still use orginal Chrome Critters under the hood?

I'm Astro user so that's why I'm interested.

Regards,

**Comment by NikolaRHristov** [comment]
Yup, that's the plan @drumsta

**Comment by drumsta** [comment]
Thanks Nikola for clarofication.

All the best in the development!

I'm closing the issue.
