### ISSUE TITLE
Unable to locate stylesheet after 1.29 update

### ISSUE THREAD

**Issue by ChrisSki** [PlayForm/Inline#68]
I haven't changed any of my config files, but critters seems to have added another `/blog/` folder while trying to locate css files. here's my astro.config

![Screenshot 2023-02-09 at 7 23 32 PM](https://user-images.githubusercontent.com/643408/217969341-24d0646d-ff71-4f94-abe1-05df2d20707d.jpg)

```
import { defineConfig } from "astro/config";
import image from "@astrojs/image";
import react from "@astrojs/react";
import critters from "astro-critters";

// https://astro.build/config
import compress from "astro-compress";

// https://astro.build/config
import sitemap from "@astrojs/sitemap";

// https://astro.build/config
export default defineConfig({
  site: "https://www.getguru.com",
  server: {
    hostname: "localhost",
    port: 3000,
  },
  base: "/blog",
  outDir: "./dist/blog",
  integrations: [
    image({
      serviceEntryPoint: "@astrojs/image/sharp",
      logLevel: "debug",
    }),
    react(),
    critters(),
    sitemap(),
  ],
});
```

**Comment by ChrisSki** [comment]
Although it does seem like something is being inlined?

![Screenshot 2023-02-09 at 8 02 43 PM](https://user-images.githubusercontent.com/643408/217973974-f3e0c0b5-a65f-4aa5-8a17-b31a8fbfed80.jpg)

**Comment by NikolaRHristov** [comment]
Should be fixed in https://github.com/astro-community/astro-critters/releases/tag/v1.1.31
