### ISSUE TITLE
Anyway to make it also remove the external <link> from the html?

### ISSUE THREAD

**Issue by gnomeria** [PlayForm/Inline#73]
Hi, thank you for building this tool. I was wondering how could we remove something like `<link href=/_astro/index.66b179d0.css rel=stylesheet>` from the built html that's already been inlined?

**Comment by NikolaRHristov** [comment]
Critters only inlines a small portion of the CSS, the one that is displayed above-the-fold. The rest is needed by your website. It is recommended to leave those intact.

**Comment by RodrigoTomeES** [comment]
@nikolaxhristov maybe this feature make sense when all your styles are critical

**Comment by NikolaRHristov** [comment]
> @nikolaxhristov maybe this feature make sense when all your styles are critical

True, this is the issue to track it https://github.com/nikolaxhristov/critters/issues/3 and it is related to https://github.com/nikolaxhristov/critters/issues/2 which needs to get fixed first.

**Comment by Suven** [comment]
@nikolaxhristov 
> Critters only inlines a small portion of the CSS, the one that is displayed above-the-fold. The rest is needed by your website. It is recommended to leave those intact.

Actually, that is a false assumption, isn't it? The critters-readme states:

> It also means Critters inlines all CSS rules used by your document, rather than only those needed for above-the-fold content.

**Comment by nikolaxhristov** [comment]
@Suven Yes, but it also means that critters includes more CSS than just that above-the-fold.

**Comment by NikolaRHristov** [comment]
@Suven I don't always give the most correct assumptions 😅

**Comment by Suven** [comment]
With the fact in mind that critters inlines everything which is needed in the initial render, the only case where the external css is still needed, is for client-side-hydrated components right? 🤔 Maybe a config option for this plugin to remove the link-tags would be nice, or am I overlooking something?

If you agree I would try and see if I am able to provide a PR.

**Comment by NikolaRHristov** [comment]
All PRs are warm-welcomed.
